version: '3.1'

services:

  wordpress_18:
    image: wordpress
    restart: always
    container_name: beltel
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: db_beltel
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - beltel_wp:/var/www/html
    depends_on:
        - db_beltel
    networks:
      - project
  db_beltel:
    image: mysql:5.7
    container_name: mysql_beltel
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_beltel:/var/lib/mysql
    networks:
      - project
networks:
  project:
    driver: bridge
volumes:
  beltel_wp:
  db_beltel:
